name: pulsain
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  carousel_slider: ^5.0.0
  dotted_border: ^2.1.0
  flutter:
    sdk: flutter
  flutter_dash: ^1.0.0
  flutter_svg: ^2.0.17
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
